### ISSUE TITLE
Modifications to add to monitors

### ISSUE THREAD

**Issue by a-Name** [abruneau/datadog_usage_monitoring#1]
Hi,
Thanks for these elements.
Here are some that need to be fixed : 
- "max(last_10m):**max**:datadog.estimated_usage.hosts{\*} > 354" must be "max(last_10m):**sum**:datadog.estimated_usage.hosts{\*} > 354"
- Daily synthetics monitors timeframe are set to **1mo** but need to be **1d**
- Synth mobile calculations are **quota\*50** but must be **quota\*100**

Cheers

**Comment by abruneau** [comment]
Thanks for you feedback
